# asn: 4200000030
network:
  version: 2
  ethernets:
    uplink:
      link-local: []
      mtu: 9000
      addresses:
      - 192.0.2.30/31
      - 2001:db8:100::30/127
    uplink-rx1:
      link-local: []
      mtu: 9000
      addresses:
      - 192.0.2.32/31
      - 2001:db8:100::32/127
    uplink-rx2:
      link-local: []
      mtu: 9000
      addresses:
      - 192.0.2.34/31
      - 2001:db8:100::34/127
  dummy-devices:
    lo42:
      link-local: []
      addresses:
      - 198.51.100.3/32
      - 2001:db8::3/128
