# asn: 4200000020
network:
  version: 2
  ethernets:
    uplink:
      link-local: []
      addresses:
      - 192.0.2.20/31
      - 2001:db8:100::20/127
  dummy-devices:
    lo42:
      link-local: []
      addresses:
      - 198.51.100.2/32
      - 2001:db8::2/128
