# asn: 4200000255
network:
  version: 2
  ethernets:
    # TX interfaces
    bird-1.6.8:
      dhcp4: false
      dhcp6: false
      link-local: []
      mtu: 9000
      # addresses:
      # - 192.0.2.11/31
      # - 2001:db8:100::11/127
    bird-2.17.2:
      dhcp4: false
      dhcp6: false
      link-local: []
      mtu: 9000
      # addresses:
      # - 192.0.2.21/31
      # - 2001:db8:100::21/127
    bird-3.1.4:
      dhcp4: false
      dhcp6: false
      link-local: []
      mtu: 9000
      # addresses:
      # - 192.0.2.31/31
      # - 2001:db8:100::31/127
    # RX1 interfaces
    bird-1.6.8-rx1:
      dhcp4: false
      dhcp6: false
      link-local: []
      mtu: 9000
      # addresses:
      # - 192.0.2.13/31
      # - 2001:db8:100::13/127
    bird-2.17.2-rx1:
      dhcp4: false
      dhcp6: false
      link-local: []
      mtu: 9000
      # addresses:
      # - 192.0.2.23/31
      # - 2001:db8:100::23/127
    bird-3.1.4-rx1:
      dhcp4: false
      dhcp6: false
      link-local: []
      mtu: 9000
      # addresses:
      # - 192.0.2.33/31
      # - 2001:db8:100::33/127
    # RX2 interfaces
    bird-1.6.8-rx2:
      dhcp4: false
      dhcp6: false
      link-local: []
      mtu: 9000
      # addresses:
      # - 192.0.2.15/31
      # - 2001:db8:100::15/127
    bird-2.17.2-rx2:
      dhcp4: false
      dhcp6: false
      link-local: []
      mtu: 9000
      # addresses:
      # - 192.0.2.25/31
      # - 2001:db8:100::25/127
    bird-3.1.4-rx2:
      dhcp4: false
      dhcp6: false
      link-local: []
      mtu: 9000
      # addresses:
      # - 192.0.2.35/31
      # - 2001:db8:100::35/127

    # RX3 interfaces
    bird-1.6.8-rx3:
      dhcp4: false
      dhcp6: false
      link-local: []
      mtu: 9000
      # addresses:
      # - 192.0.2.15/31
      # - 2001:db8:100::15/127
    bird-2.17.2-rx3:
      dhcp4: false
      dhcp6: false
      link-local: []
      mtu: 9000
      # addresses:
      # - 192.0.2.25/31
      # - 2001:db8:100::25/127
    bird-3.1.4-rx3:
      dhcp4: false
      dhcp6: false
      link-local: []
      mtu: 9000
      # addresses:
      # - 192.0.2.35/31
      # - 2001:db8:100::35/127
    # RX4 interfaces
    bird-1.6.8-rx4:
      dhcp4: false
      dhcp6: false
      link-local: []
      mtu: 9000
      # addresses:
      # - 192.0.2.15/31
      # - 2001:db8:100::15/127
    bird-2.17.2-rx4:
      dhcp4: false
      dhcp6: false
      link-local: []
      mtu: 9000
      # addresses:
      # - 192.0.2.25/31
      # - 2001:db8:100::25/127
    bird-3.1.4-rx4:
      dhcp4: false
      dhcp6: false
      link-local: []
      mtu: 9000
      # addresses:
      # - 192.0.2.35/31
      # - 2001:db8:100::35/127
  dummy-devices:
    lo42:
      link-local: []
      addresses:
      - 198.51.100.255/32
      - 2001:db8::ffff/128
