# asn: 4200000200
network:
  version: 2
  ethernets:
    uplink:
      link-local: []
      addresses:
      - 192.0.2.200/31
      - 2001:db8:100::200/127
  dummy-devices:
    lo42:
      link-local: []
      addresses:
      - 198.51.100.200/32
      - 2001:db8::200/128
