# asn: 4200000010
network:
  version: 2
  ethernets:
    uplink:
      link-local: []
      addresses:
      - 192.0.2.10/31
      - 2001:db8:100::10/127
  dummy-devices:
    lo42:
      link-local: []
      addresses:
      - 198.51.100.1/32
      - 2001:db8::1/128
