# asn: 4200000010
network:
  version: 2
  ethernets:
    uplink:
      mtu: 9000
      addresses:
      - 192.0.2.10/31
      - 2001:db8:100::10/127
    uplink-rx1:
      mtu: 9000
      addresses:
      - 192.0.2.12/31
      - 2001:db8:100::12/127
    uplink-rx2:
      mtu: 9000
      addresses:
      - 192.0.2.14/31
      - 2001:db8:100::14/127
    uplink-rx3:
      mtu: 9000
      addresses:
      - 192.0.2.16/31
      - 2001:db8:100::16/127
    uplink-rx4:
      mtu: 9000
      addresses:
      - 192.0.2.18/31
      - 2001:db8:100::18/127
  dummy-devices:
    lo42:
      addresses:
      - 198.51.100.1/32
      - 2001:db8::1/128
      routes:
      - to: 198.18.0.0/15
        type: blackhole
        via: "0.0.0.0"
        metric: 240
      - to: 2001:db8:ffff::/56
        type: blackhole
        via: "::"
        metric: 240