# asn: 4200000010
network:
  version: 2
  ethernets:
    uplink:
      link-local: []
      mtu: 9000
      addresses:
      - 192.0.2.10/31
      - 2001:db8:100::10/127
    uplink-rx1:
      link-local: []
      mtu: 9000
      addresses:
      - 192.0.2.12/31
      - 2001:db8:100::12/127
    uplink-rx2:
      link-local: []
      mtu: 9000
      addresses:
      - 192.0.2.14/31
      - 2001:db8:100::14/127
  dummy-devices:
    lo42:
      link-local: []
      addresses:
      - 198.51.100.1/32
      - 2001:db8::1/128
