# asn: 4200000020
network:
  version: 2
  ethernets:
    uplink:
      mtu: 9000
      addresses:
      - 192.0.2.20/31
      - 2001:db8:100::20/127
    uplink-rx1:
      mtu: 9000
      addresses:
      - 192.0.2.22/31
      - 2001:db8:100::22/127
    uplink-rx2:
      mtu: 9000
      addresses:
      - 192.0.2.24/31
      - 2001:db8:100::24/127
  dummy-devices:
    lo42:
      addresses:
      - 198.51.100.2/32
      - 2001:db8::2/128
      routes:
      - to: 198.18.0.0/15
        type: blackhole
        via: "0.0.0.0"
        metric: 240
      - to: 2001:db8:ffff::/56
        type: blackhole
        via: "::"
        metric: 240